controller_list:
  - name: fake_arm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - base
      - shoulder
      - elbow
      - pitch
      - roll
  - name: fake_gripper_group_controller
    type: $(arg fake_execution_type)
    joints:
      - roll
      - gripper_finger_left_joint
      - gripper_finger_right_joint
initial:  # Define initial robot poses per group
  - group: arm_group
    pose: home