arm_position_contr:
  type: position_controllers/JointTrajectoryController
  joints:
    []
  gains:
    {}
arm_velocity_contr:
  type: velocity_controllers/JointTrajectoryController
  joints:
    []
  gains:
    {}