controller_list:
  - name: arm_position_contr
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      []
  - name: arm_velocity_contr
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      []
  - name: arm_follow_joint_trajectory
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      []
  - name: gripper_contr
    action_ns: gripper_action
    type: GripperCommand
    default: True
    joints:
      []