scorbot:
  arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - base
      - shoulder
      - elbow
      - pitch
      - roll
    contraints:
      goal_time: 0.6
      stopped_velocity_tolerances: 0.05
      base: {trajectory: 0.01, goal: 0,1}
      shoulder: {trajectory: 0.01, goal: 0,1}
      elbow: {trajectory: 0.01, goal: 0,1}
      pitch: {trajectory: 0.01, goal: 0,1}
      roll: {trajectory: 0.01, goal: 0,1}
    stop_trajectory_duration: 0.5
    state_publish_rate: 25
    action_monitor_ rate: 10
  
  gripper_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - gripper_finger_right_joint
      - gripper_finger_left_joint
    contraints:
      goal_time: 0.6
      stopped_velocity_tolerances: 0.05
      gripper_finger_right_joint: {trajectory: 0.01, goal: 0,1}
      gripper_finger_left_joint: {trajectory: 0.01, goal: 0,1}
    stop_trajectory_duration: 0.5
    state_publish_rate: 25
    action_monitor_ rate: 10