// Generated by gencpp from file sim_scorbot_master/JointTrajectory.msg
// DO NOT EDIT!


#ifndef SIM_SCORBOT_MASTER_MESSAGE_JOINTTRAJECTORY_H
#define SIM_SCORBOT_MASTER_MESSAGE_JOINTTRAJECTORY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace sim_scorbot_master
{
template <class ContainerAllocator>
struct JointTrajectory_
{
  typedef JointTrajectory_<ContainerAllocator> Type;

  JointTrajectory_()
    : header()
    , points()  {
    }
  JointTrajectory_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , points(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::sim_scorbot_master::JointTrajectory_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sim_scorbot_master::JointTrajectory_<ContainerAllocator> const> ConstPtr;

}; // struct JointTrajectory_

typedef ::sim_scorbot_master::JointTrajectory_<std::allocator<void> > JointTrajectory;

typedef boost::shared_ptr< ::sim_scorbot_master::JointTrajectory > JointTrajectoryPtr;
typedef boost::shared_ptr< ::sim_scorbot_master::JointTrajectory const> JointTrajectoryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sim_scorbot_master::JointTrajectory_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sim_scorbot_master::JointTrajectory_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sim_scorbot_master::JointTrajectory_<ContainerAllocator1> & lhs, const ::sim_scorbot_master::JointTrajectory_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sim_scorbot_master::JointTrajectory_<ContainerAllocator1> & lhs, const ::sim_scorbot_master::JointTrajectory_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sim_scorbot_master

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sim_scorbot_master::JointTrajectory_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sim_scorbot_master::JointTrajectory_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sim_scorbot_master::JointTrajectory_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sim_scorbot_master::JointTrajectory_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sim_scorbot_master::JointTrajectory_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sim_scorbot_master::JointTrajectory_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sim_scorbot_master::JointTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff3fd76c56194eb1ef5652fa7b44a08a";
  }

  static const char* value(const ::sim_scorbot_master::JointTrajectory_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff3fd76c56194eb1ULL;
  static const uint64_t static_value2 = 0xef5652fa7b44a08aULL;
};

template<class ContainerAllocator>
struct DataType< ::sim_scorbot_master::JointTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sim_scorbot_master/JointTrajectory";
  }

  static const char* value(const ::sim_scorbot_master::JointTrajectory_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sim_scorbot_master::JointTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32[] points # num_juntas x points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::sim_scorbot_master::JointTrajectory_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sim_scorbot_master::JointTrajectory_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointTrajectory_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sim_scorbot_master::JointTrajectory_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sim_scorbot_master::JointTrajectory_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIM_SCORBOT_MASTER_MESSAGE_JOINTTRAJECTORY_H
