/universal_teleop:
  ros__parameters:
    keys:
      base_cw: 113 
      base_ccw: 97 
      shoulder_down: 115 
      shoulder_up: 119 
      elbow_down: 100 
      elbow_up : 101 
      wrist_down: 102 
      wrist_up: 114 
      rotate_cw: 103 
      rotate_ccw: 116 
      override: 120 
      stop: 122 
      claw_catch: 49 
      claw_release: 50 
      home: 104 
      slow: 121 
    joy_axes:
      base: 6
      shoulder: 7
    joy_buttons:
      elbow_down: 1
      elbow_up : 2
      wrist_down: 3
      wrist_up: 4
      rotate_ccw: 5
      rotate_cw: 6
      override: 7
      stop: 8
      claw_catch: 9
      claw_release: 10
      home: 11
      slow: 12